spring:
  #Datasource config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://124.222.174.20:3306/user_center
    username: dogyupi
    password: yupi666
  #session失效时间 秒 86400一天
  session:
    timeout: 86400
